import { Delta } from "block-kit-delta";

export const INIT = new Delta({
  ops: [
    { insert: "Block Kit" },
    { insert: "\n", attributes: { align: "center", heading: "h1" } },
    { insert: "纸上得来终觉浅，绝知此事要躬行。从零实现富文本编辑器，基于" },
    { attributes: { "inline-code": "true" }, insert: "ContentEdiable" },
    { insert: "构建" },
    { attributes: { "inline-code": "true" }, insert: "MVC" },
    { insert: "架构，设计可扩展的" },
    { insert: "Controller", attributes: { "inline-code": "true" } },
    { insert: "层，以线性数据结构维护" },
    { insert: "Model", attributes: { "inline-code": "true" } },
    { insert: "层，实现可组合视图框架的" },
    { insert: "View", attributes: { "inline-code": "true" } },
    { insert: "层，当前所有功能都是基于插件化定义实现。" },
    { insert: "\n" },
    { insert: "行内结构" },
    { attributes: { heading: "h2" }, insert: "\n" },
    { insert: "支持 " },
    { attributes: { bold: "true" }, insert: "加粗" },
    { insert: "、" },
    { attributes: { italic: "true" }, insert: "斜体" },
    { insert: "、" },
    { attributes: { underline: "true" }, insert: "下划线" },
    { insert: "、" },
    { attributes: { strike: "true" }, insert: "删除线" },
    { insert: "、" },
    { attributes: { "inline-code": "true" }, insert: "行内代码" },
    { insert: "、" },
    { insert: "字体颜色", attributes: { color: "rgb(36, 91, 219)" } },
    { insert: "、" },
    { attributes: { background: "rgba(186, 206, 253, 0.7)" }, insert: "背景颜色" },
    { insert: "、" },
    { insert: "字体大小", attributes: { "font-size": "14" } },
    { insert: " 等" },
    { insert: "\n", attributes: { align: "center" } },
    { insert: "段落结构" },
    { insert: "\n", attributes: { heading: "h2" } },
    { insert: "行高" },
    { insert: "\n", attributes: { heading: "h3" } },
    { insert: "2.0", attributes: { "inline-code": "true" } },
    { insert: "倍行高" },
    { insert: "\n", attributes: { "line-height": "2.0" } },
    { insert: "对齐" },
    { insert: "\n", attributes: { heading: "h3" } },
    { insert: "居左对齐" },
    { insert: "\n" },
    { insert: "无序列表" },
    { insert: "\n", attributes: { heading: "h3" } },
    { insert: "一级无序列表" },
    { insert: "\n", attributes: { list: "bullet" } },
    { insert: "二级无序列表" },
    { attributes: { "indent-level": "1", "list": "bullet" }, insert: "\n" },
    { insert: "三级无序列表" },
    { attributes: { "indent-level": "2", "list": "bullet" }, insert: "\n" },
    { insert: "有序列表" },
    { insert: "\n", attributes: { heading: "h3" } },
    { insert: "一级有序列表" },
    { insert: "\n", attributes: { "list-start": "1", "list": "order" } },
    { insert: "二级有序列表" },
    { attributes: { "list-start": "1", "indent-level": "1", "list": "order" }, insert: "\n" },
    { insert: "三级有序列表" },
    { attributes: { "list-start": "1", "indent-level": "2", "list": "order" }, insert: "\n" },
    { insert: "块级结构" },
    { attributes: { heading: "h2" }, insert: "\n" },
    { insert: "图片" },
    { insert: "\n", attributes: { heading: "h3" } },
    {
      attributes: { image: "true", src: "./favicon.ico", width: "200", height: "200" },
      insert: " ",
    },
    { insert: "\n" },
    { insert: "分割线" },
    { insert: "\n", attributes: { heading: "h3" } },
    { attributes: { divider: "true" }, insert: " " },
    { insert: "\n" },
    { insert: "嵌入结构" },
    { attributes: { heading: "h2" }, insert: "\n" },
    { attributes: { mention: "true", name: "Czy" }, insert: " " },
    { insert: "\n" },
  ],
});
